/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulp.vistas;

import java.util.logging.Level;
import java.util.logging.Logger;
import ulp.modelo.Conexion;
import ulp.modelo.Materia;
import ulp.modelo.MateriaData;

/**
 *
 * @author programador
 */
public class VistaMateria extends javax.swing.JInternalFrame {

    /**
     * Creates new form VistaMateria
     */
    private MateriaData materiaData;
    private Conexion conexion;
    
    public VistaMateria() {
        initComponents();
        try {
            initComponents();
            conexion= new Conexion();
            materiaData= new MateriaData(conexion);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaAlumno.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tIdMateria = new javax.swing.JTextField();
        tNombreMateria = new javax.swing.JTextField();
        bBuscarMateria = new javax.swing.JButton();
        bGuardarMateria = new javax.swing.JButton();
        bBorrarMateria = new javax.swing.JButton();
        bActualizarMateria = new javax.swing.JButton();
        bLimpiarMateria = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 102, 102));
        jLabel1.setText("-MATERIAS-");

        jLabel3.setText("ID");

        jLabel4.setText("NOMBRE:");

        bBuscarMateria.setText("Buscar");
        bBuscarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBuscarMateriaActionPerformed(evt);
            }
        });

        bGuardarMateria.setText("Guardar");
        bGuardarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bGuardarMateriaActionPerformed(evt);
            }
        });

        bBorrarMateria.setText("Borrar");
        bBorrarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bBorrarMateriaActionPerformed(evt);
            }
        });

        bActualizarMateria.setText("Actualizar");
        bActualizarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bActualizarMateriaActionPerformed(evt);
            }
        });

        bLimpiarMateria.setText("Limpiar");
        bLimpiarMateria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bLimpiarMateriaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tNombreMateria, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(tIdMateria))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(bBuscarMateria))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(159, 159, 159)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(bGuardarMateria)
                .addGap(45, 45, 45)
                .addComponent(bBorrarMateria)
                .addGap(45, 45, 45)
                .addComponent(bActualizarMateria)
                .addGap(45, 45, 45)
                .addComponent(bLimpiarMateria)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tIdMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bBuscarMateria))
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tNombreMateria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bGuardarMateria)
                    .addComponent(bBorrarMateria)
                    .addComponent(bActualizarMateria)
                    .addComponent(bLimpiarMateria))
                .addGap(23, 23, 23))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bGuardarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bGuardarMateriaActionPerformed
        String nombre = tNombreMateria.getText();
        Materia materia = new Materia(nombre);
        materiaData.guardarMateria(materia);
        tIdMateria.setText(materia.getId()+"");
    }//GEN-LAST:event_bGuardarMateriaActionPerformed

    private void bBorrarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBorrarMateriaActionPerformed
        int id = Integer.parseInt(tIdMateria.getText());
        materiaData.borrarMateria(id);
    }//GEN-LAST:event_bBorrarMateriaActionPerformed

    private void bActualizarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bActualizarMateriaActionPerformed
        if(tIdMateria.getText() != null){
            
            int idMateria = Integer.parseInt(tIdMateria.getText());
            String nombre = tNombreMateria.getText();
            Materia materia = new Materia(idMateria, nombre);
            materiaData.actualizarMateria(materia);
        }
    }//GEN-LAST:event_bActualizarMateriaActionPerformed

    private void bLimpiarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bLimpiarMateriaActionPerformed
       tIdMateria.setText("");
       tNombreMateria.setText("");
    }//GEN-LAST:event_bLimpiarMateriaActionPerformed

    private void bBuscarMateriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bBuscarMateriaActionPerformed
        int id = Integer.parseInt(tIdMateria.getText());
        Materia materia = materiaData.buscarMateria(id);
        if(materia != null){
            tNombreMateria.setText(materia.getNombre());
        }
    }//GEN-LAST:event_bBuscarMateriaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bActualizarMateria;
    private javax.swing.JButton bBorrarMateria;
    private javax.swing.JButton bBuscarMateria;
    private javax.swing.JButton bGuardarMateria;
    private javax.swing.JButton bLimpiarMateria;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField tIdMateria;
    private javax.swing.JTextField tNombreMateria;
    // End of variables declaration//GEN-END:variables
}
