/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ulp.vistas;

import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;
import ulp.modelo.Alumno;
import ulp.modelo.AlumnoData;
import ulp.modelo.Conexion;
import ulp.modelo.CursadaData;
import ulp.modelo.Materia;

/**
 *
 * @author programador
 */
public class VistaInscripciones extends javax.swing.JInternalFrame {

    private Alumno alumno;
    private Conexion conexion;
    private AlumnoData ad;
    private CursadaData cd;
    private DefaultTableModel modelo;
    
    /**
     * Creates new form VistaCursada
     */
    public VistaInscripciones() {
        try {
            initComponents();
            conexion = new Conexion();
            ad = new AlumnoData(conexion);
            List<Alumno> lista = ad.obtenerAlumnos();
            for(Alumno it: lista){
                jcAlumnos.addItem(it);
            }
            modelo= new DefaultTableModel();
            cd= new CursadaData(conexion);
            armarCabeceraTabla();
            
            
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(VistaInscripciones.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jcAlumnos = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jrbNoInscriptas = new javax.swing.JRadioButton();
        jrbInscriptas = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMateria = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 153));
        jLabel1.setText("FORMULARIO INSCRIPCION");

        jLabel2.setText("Alumnos:");

        jLabel3.setText("Listado de materias");

        jrbNoInscriptas.setText("No inscriptas");
        jrbNoInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbNoInscriptasActionPerformed(evt);
            }
        });

        jrbInscriptas.setText("Inscriptas");
        jrbInscriptas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbInscriptasActionPerformed(evt);
            }
        });

        jtMateria.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jtMateria);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(jrbInscriptas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jrbNoInscriptas)
                .addGap(128, 128, 128))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel2)
                        .addGap(56, 56, 56)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jcAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jLabel3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jcAlumnos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbNoInscriptas)
                    .addComponent(jrbInscriptas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 42, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jrbInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbInscriptasActionPerformed
        jrbNoInscriptas.setSelected(false);
    }//GEN-LAST:event_jrbInscriptasActionPerformed

    private void jrbNoInscriptasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbNoInscriptasActionPerformed
        jrbInscriptas.setSelected(false);
    }//GEN-LAST:event_jrbNoInscriptasActionPerformed
    public void armarCabeceraTabla(){
        ArrayList<Object> columnas = new ArrayList<Object>();
         columnas.add("ID");
         columnas.add("Nombre");
         for(Object it: columnas){
             
             modelo.addColumn(it);
         }
         jtMateria.setModel(modelo);
    
}
    public void borrarFilas(){
        int a = modelo.getRowCount() - 1;
        
        for(int i=a; i>=0; i--){
            modelo.removeRow(i);
        }
    }
    
    public void cargaDatasInscriptas(){
        borrarFilas();
        
        
        alumno = (Alumno)jcAlumnos.getSelectedItem();
        List<Materia> listaMaterias = cd.obtenerMateriasCursadas(alumno.getId());
        
        for(Materia m: listaMaterias){
            modelo.addRow(new Object[]{m.getId(), m.getNombre()});
        }
       
    }
    public void cargaDatasNoInscriptas(){
          borrarFilas();
        
        
        alumno = (Alumno)jcAlumnos.getSelectedItem();
        List<Materia> listaMaterias = cd.obtenerMateriasNOCursadas(alumno.getId());
        
        for(Materia m: listaMaterias){
            modelo.addRow(new Object[]{m.getId(), m.getNombre()});
        }
       
      } 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<Alumno> jcAlumnos;
    private javax.swing.JRadioButton jrbInscriptas;
    private javax.swing.JRadioButton jrbNoInscriptas;
    private javax.swing.JTable jtMateria;
    // End of variables declaration//GEN-END:variables
}
